compute: single-node-standard-f8
tasks:
  details-transformation:
    task-class: RunTransformationTask
    task-config: 
      transformation-class: customerio.CustomerioTransactionalMessageDetailsTransform