databricks-config:
  host: "$DATABRICKS_HOST"
  token: "$DATABRICKS_TOKEN"
azure-storage-connection-string: "$DEV_AZURE_STORAGE_CONNECTION_STRING"
redis-config:
  host: "$DEV_REDIS_HOST"
  port: "$DEV_REDIS_PORT"
  password: "$DEV_REDIS_PASSWORD"
postgres-config:
  host: "$DEV_PG_HOST"
  port: "$DEV_PG_PORT"
  database: "$DEV_PG_DATABASE"
  user: "$DEV_PG_USER"
  password: "$DEV_PG_PASSWORD"
  
