name: Alert Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Determine parent count of HEAD
        run: |
          # Count all parents of the HEAD commit
          parent_count=$(git rev-list --no-walk --count HEAD^@)
          echo "Commit has $parent_count parent(s)."
          # If only one parent, it's a direct push → block it
          if [ "$parent_count" -eq 1 ]; then
            echo "❌ Direct push to 'main' is not allowed. Please use a pull request."
            exit 1
          fi
      - name: Allow merge commits
        run: echo "✅ Merge commit detected; allowing push."
